// Code generated by sqlc. DO NOT EDIT.

package tutorial

import (
	"database/sql"
)

type Person struct {
	ID        int32
	Firstname sql.NullString
	Lastname  sql.NullString
	Email     sql.NullString
}
